config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :set_search
  def index
  end

  def search
    @events = @q.result(distinct: true)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @events }
    end
  end


  private
  def set_search
    @q = Event.search(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Event Index</title>
</head>
<body>
<%= search_form_for(@q, url:search_events_path,method: :get) do |f| %>
  <div>
    <%= f.label :name_cont %>
    <%= f.search_field :name_cont %>
  </div>
  <div>
    <%= f.label :body_cont %>
    <%= f.search_field :body_cont %>
  </div>
  <%= f.submit %>
<% end %>
</div>
</body>
</html>

app/views/events/search.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Event Search</title>
</head>
<body>
<h1>Search Result</h1>
  <div>
    <% @events.each do |event| %>
      <div>
        <%= event.name %>
        <%= event.body %>
      </div>
    <% end %>
  </div>
<div>
  <%= link_to 'Back', events_path %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>